# Rust 代码格式化配置
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# 导入分组
reorder_imports = true
reorder_modules = true

# 函数签名
fn_params_layout = "Tall"

# 其他
use_field_init_shorthand = true
use_try_shorthand = true
